Repository rubrikinc/rubrik-scripts-for-powershell, pull requests merged in 2019-03, with the labels that each got.

#52 minor typo
  RubrikPoSHHowTo/1-GettingStarted.ps1
Labels: kind-bug

#56 Storage Policy to SLA Protection Script
  StoragePolicytoSLAv2.ps1
Labels: area-cdm, kind-enhancement, priority-p1

#57 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: kind-docs

#58 Create pull_request_template.md
  .github/pull_request_template.md
Labels: kind-docs
